openapi: 3.0.2
info:
  title: Shoppin Center
  description: >-
     This API provides us with different information about the users to use in the shopping centre to provide a better experience in the visit
  version: '1.0'
  termsOfService: 'http://spilab.es/'
  contact:
    name: Spilab
    url: 'http://spilab.es/'
    email: spilab.uex@gmail.com
tags:
  - name: User
paths:
  /temperature:
    get:
      summary: Gets the environment temperature
      operationId: getTemperature
      tags:
      - User
      x-dac:
        operand: User.temperature
        operator:
          type: math
          name: AVG
        conditions:
          precision: 200
          temporal: 1500 
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
  /location:
    get:
      summary: Gets the current location
      operationId: getLocation
      tags:
      - User
      x-dac:
        operand: User.location
        operator:
          type: specfic
          name: heatmap
        conditions:
          precision: 200
          temporal: 1500 
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
  /music:
    get:
      summary: Gets a list of favourite music genres
      operationId: getMusic
      tags:
      - User
      x-dac:
        operand: User.music
        operator:
          type: specfic
          name: selectMusic
        conditions:
          precision: 200
          temporal: 1500 
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
    
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "684B442C9"
        temperature:
          type: number
          format: double
          example: 36.7
        music:
          $ref: '#/components/schemas/MusicArray'
        location:
          $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: double
          example: 38.48492
        longitude:
          type: number
          format: double
          example: -6.58794
    MusicArray:
      type: array
      items:
        type: string
        example: "[pop,rock,indie]"
  responses:
    
    '200':
      description: Successful response
      content:
       application/json:
        schema:
          $ref: '#/components/schemas/User'
    '404':
      description: Not found response
      content:
        text/plain:
          schema:
            title: Endpoint not found
            type: string
            example: Not found
